apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-graylog-secret
type: Opaque
data:
  password_secret: {{ .Values.graylog.passwordSecret | b64enc }}
  root_password_sha2: {{ .Values.graylog.rootPasswordSha2 | b64enc }}
