apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-graylog
  labels:
    app: graylog
spec:
  type: {{ .Values.service.type }}
  selector:
    app: graylog
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 9000
    - name: gelf
      protocol: TCP
      port: {{ .Values.service.gelfPort }}
      targetPort: 12201
