apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-petclinic
  template:
    metadata:
      labels:
        app: spring-petclinic
    spec:
      containers:
      - name: spring-petclinic
        image: cr.yandex/crp8nu6sshurc917bput/my-registry/spring-petclinic
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
