name: CI Pipeline

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build and test with Maven
        run: mvn -B clean verify

      - name: Build Docker image
        run: docker build -t cr.yandex/crp8nu6sshurc917bput/my-registry/spring-petclinic .

      - name: Push Docker image
        env:
          YC_TOKEN: ${{ secrets.YC_TOKEN }}
        run: |
          echo $YC_TOKEN | docker login -u oauth --password-stdin cr.yandex
          docker push cr.yandex/crp8nu6sshurc917bput/my-registry/spring-petclinic .
